@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
              <h1>Ini paragraph</h1>
              <hr>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate architecto magni suscipit, minima necessitatibus cum. Earum, voluptates autem alias eum nulla aspernatur sit dolorum et distinctio dolor? Illo, voluptatem sunt delectus consequatur dolor molestias vitae! Vero pariatur ratione saepe fugiat eaque blanditiis distinctio sint nobis placeat architecto consectetur qui accusantium repellat ut officia suscipit assumenda, quae deserunt praesentium aperiam necessitatibus. Natus explicabo nulla porro delectus dolores fuga laborum quae eaque minus iste velit harum quia animi quasi, sunt atque! Nam unde necessitatibus dolor laboriosam iusto possimus debitis, inventore mollitia totam delectus dolorem repudiandae, suscipit placeat commodi? Debitis libero quas neque numquam tenetur perspiciatis, quos temporibus nesciunt, ullam enim, ad hic fugiat totam nisi blanditiis. Saepe error expedita quasi perferendis placeat, excepturi animi porro ipsam ea id dolor quaerat assumenda qui esse exercitationem, aspernatur earum consequuntur. Praesentium iusto dolorum maxime porro a fugit, reiciendis architecto est repellat suscipit mollitia earum libero iure, accusamus qui rem quia autem impedit debitis eligendi vero vitae repellendus illum. Quaerat recusandae dolores, quisquam nam obcaecati iusto quia molestias accusantium sint asperiores aut eum similique ipsam? Et consectetur sed deleniti laboriosam suscipit culpa quidem similique ab nihil! Modi nihil provident, tenetur eveniet magni ipsum veritatis itaque eaque.</p>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At odit ex tenetur ipsam suscipit repudiandae ipsa veniam animi obcaecati ducimus culpa veritatis architecto numquam eligendi deserunt vero, non quia, accusamus eius officiis, corrupti earum possimus aspernatur. Libero fuga, aut molestiae quibusdam hic, velit doloribus, laboriosam dicta maiores rem placeat quia vitae dolorem nisi soluta nihil suscipit et magnam corporis tempora. Sit, saepe assumenda distinctio, nostrum quos impedit eos eius voluptatibus cupiditate inventore quae iure ex maxime quaerat nesciunt. Facilis quasi molestias at doloribus tenetur voluptatum. Fugit voluptatem saepe vel animi, quasi harum ab aliquam similique debitis, quibusdam, eaque laboriosam doloribus sequi aliquid sapiente? Rem dolores ut fugiat cumque corporis eos exercitationem nostrum deleniti nemo eligendi totam, sequi ad accusamus dignissimos asperiores quisquam sit et beatae vitae veniam ipsam obcaecati ducimus in. Debitis quis inventore, reiciendis nisi voluptatem nulla? Eaque voluptas pariatur itaque quidem atque nostrum quas, ducimus magnam? Aut distinctio debitis, dicta sint ducimus consequatur voluptates quis voluptatum, quam non laboriosam iure voluptatibus eum aspernatur nisi. Hic consectetur voluptatum omnis maxime excepturi dolores, corporis mollitia molestiae molestias aspernatur sunt quod eum enim rerum quos doloremque non facilis blanditiis. Praesentium similique quia ex, aliquid laboriosam illum ipsa vero ea, quasi possimus quaerat officia voluptatibus. Rerum nemo repellendus, placeat dolorem totam corrupti provident maxime nulla atque neque reprehenderit sequi modi veritatis velit quae cupiditate quaerat cum id fuga tempora, perferendis earum. Adipisci quae praesentium quis quidem tempore rem magnam esse consequatur sapiente accusantium, cupiditate architecto facere repellat at illum reiciendis aliquam ipsum.</p>
        </div>
    </div>
</div>
@endsection
